---
sidebar: sidebar 
permalink: concept-privacy.html 
keywords: privacy, data privacy, credentials, access to credentials, hashicorp vault 
summary: 'NetApp ne dispose d"aucun identifiant que vous fournissez lors de l"utilisation du service de copie et de synchronisation BlueXP. Les informations d"identification sont stockées directement sur l"ordinateur du courtier de données, qui réside dans votre réseau.' 
---
= Confidentialité des données
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp ne dispose d'aucun identifiant que vous fournissez lors de l'utilisation du service de copie et de synchronisation BlueXP. Les informations d'identification sont stockées directement sur l'ordinateur du courtier de données, qui réside dans votre réseau.

Selon la configuration que vous choisissez, la copie et la synchronisation BlueXP peuvent vous demander des informations d'identification lorsque vous créez une relation. Par exemple, lors de la configuration d'une relation qui inclut un serveur SMB, ou lors du déploiement du courtier en données dans AWS.

Ces informations d'identification sont toujours enregistrées directement dans le data broker lui-même. Le courtier en données réside sur une machine de votre réseau, qu'elle soit hébergée sur site ou dans votre compte cloud. Les informations d'identification ne sont jamais mises à la disposition de NetApp.

Les informations d'identification sont chiffrées localement sur la machine du courtier de données à l'aide de HashiCorp Vault.
