---
sidebar: sidebar 
permalink: faq.html 
keywords: community, forums, help, support, videos, faq, getting help, permissions, access control lists, acls, preserve, preserving, troubleshooting, support, encryption, smb 
summary: 'Vous pouvez obtenir de l"aide sur la copie et la synchronisation BlueXP et obtenir plus d"informations via diverses ressources, notamment des forums, des services de discussion et des vidéos.' 
---
= FAQ technique sur la copie et la synchronisation BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Cette FAQ peut vous aider si vous cherchez simplement une réponse rapide à une question.



== Pour commencer

Voici quelques questions relatives à la mise en route de la copie et de la synchronisation BlueXP.



=== Fonctionnement de la copie et de la synchronisation BlueXP

La copie et la synchronisation BlueXP utilisent le logiciel NetApp Data Broker pour synchroniser les données entre une source et une cible (appelé relation _sync_).

Un groupe de courtiers de données contrôle les relations de synchronisation entre vos sources et vos cibles. Une fois que vous avez configuré une relation de synchronisation, la copie et la synchronisation BlueXP analyse votre système source et les répartit en plusieurs flux de réplication pour les transmettre aux données cible sélectionnées.

Après la copie initiale, le service synchronise toutes les données modifiées en fonction de la planification que vous avez définie.



=== Comment fonctionne l'essai gratuit de 14 jours ?

L'essai gratuit de 14 jours débute lorsque vous vous inscrivez au service de copie et de synchronisation BlueXP. Vous n'êtes pas soumis aux frais NetApp liés aux relations de copie et de synchronisation BlueXP que vous créez pendant 14 jours. Cependant, tous les frais de ressources liés aux courtiers de données que vous déployez sont toujours applicables.



=== Combien coûte la copie et la synchronisation BlueXP ?

La copie et la synchronisation BlueXP sont associées à deux types de coûts : les frais de service et les frais de ressources.

*Frais de service*

Pour le paiement à l'utilisation, les frais de service de copie et de synchronisation BlueXP sont facturés à l'heure, en fonction du nombre de relations de synchronisation créées.

* https://aws.amazon.com/marketplace/pp/B01LZV5DUJ["Consultez les tarifs à la carte dans AWS"^]
* https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Voir les tarifs annuels dans AWS"^]
* https://azuremarketplace.microsoft.com/en-us/marketplace/apps/netapp.cloud-sync-service?tab=PlansAndPrice["Voir les tarifs à Azure"^]


Les licences de copie et de synchronisation BlueXP sont également disponibles auprès de votre conseiller NetApp. Chaque licence permet 20 relations de synchronisation pendant 12 mois.

link:concept-licensing.html["En savoir plus sur les licences"].


NOTE: Les relations de copie et de synchronisation BlueXP  sont gratuites pour Azure NetApp Files.

*Frais de ressources*

Les frais de ressources sont liés aux coûts de calcul et de stockage pour l'exécution du courtier de données dans le cloud.



=== Comment la copie et la synchronisation BlueXP sont-elles facturées, et comment gérer mon abonnement ?

Il existe deux façons de payer les relations de synchronisation après la fin de votre essai gratuit de 14 jours. La première option consiste à vous abonner à AWS ou Azure, ce qui vous permet de payer à votre gré ou de payer chaque année. La deuxième option consiste à acheter des licences directement auprès de NetApp. Dans chaque cas, votre abonnement sera géré via votre fournisseur Marketplace et *NOT* via l'interface utilisateur de copie et de synchronisation BlueXP.



=== Est-il possible d'utiliser la copie et la synchronisation BlueXP en dehors du cloud ?

Oui, vous pouvez utiliser la copie et la synchronisation BlueXP dans une architecture non cloud. La source et la cible peuvent résider sur le site, de sorte que le logiciel de courtier en données peut être utilisé.

Notez les points clés suivants sur l'utilisation de la copie et de la synchronisation BlueXP en dehors du cloud :

* Un groupe de courtiers en données doit disposer d'une connexion Internet pour communiquer avec le service de copie et de synchronisation BlueXP.
* Si vous n'achetez pas de licence directement auprès de NetApp, vous avez besoin d'un compte AWS ou Azure pour la facturation du service de copie et de synchronisation PAYGO BlueXP.




=== Comment accéder à la copie et à la synchronisation BlueXP ?

La copie et la synchronisation BlueXP sont disponibles depuis le site Web de BlueXP sous l'onglet *Sync*.



=== Qu'est-ce qu'un groupe de courtiers de données ?

Chaque courtier appartient à un groupe de courtier en données. Le regroupement de courtiers de données permet d'améliorer les performances des relations synchronisées.



== Sources et cibles prises en charge

Les questions suivantes concernent la source et les cibles prises en charge dans une relation de synchronisation.



=== Quelles sont les sources et les cibles prises en charge par la copie et la synchronisation BlueXP ?

La copie et la synchronisation BlueXP prennent en charge de nombreux types de relations de synchronisation. link:reference-supported-relationships.html["Afficher la liste complète"].



=== Quelles sont les versions de NFS et SMB prises en charge par la copie et la synchronisation BlueXP ?

La copie et la synchronisation BlueXP prennent en charge NFS version 3 et ultérieures, ainsi que SMB version 1 et versions ultérieures.

link:reference-requirements.html["En savoir plus sur les exigences de synchronisation"].



=== Quand Amazon S3 est la cible, les données peuvent-elles être hiérarchisées vers une classe de stockage S3 spécifique ?

Oui, vous pouvez choisir une classe de stockage S3 spécifique lorsque AWS S3 est la cible :

* Standard (il s'agit de la classe par défaut)
* Le Tiering intelligent
* Accès autonome et peu fréquent
* Un seul accès à Zone-Infrequent
* Archives profondes des Glaciers
* Récupération flexible Glacier
* Récupération instantanée Glacier




=== Qu'en est-il des niveaux de stockage pour le stockage Azure Blob ?

Vous pouvez choisir un niveau de stockage spécifique à Azure Blob lorsqu'un conteneur Blob est la cible :

* Stockage à chaud
* Stockage cool




=== Prenez-vous en charge les tiers de stockage Google Cloud ?

Oui, vous pouvez choisir une classe de stockage spécifique lorsqu'un compartiment Google Cloud Storage est la cible :

* Standard
* Nearline
* Ligne de refroidissement
* Archivage




== Mise en réseau

Les questions suivantes concernent les exigences de mise en réseau pour la copie et la synchronisation BlueXP.



=== Quelles sont les exigences de mise en réseau pour la copie et la synchronisation BlueXP ?

L'environnement de copie et de synchronisation BlueXP nécessite qu'un groupe de courtiers en données soit connecté à la source et à la cible via le protocole ou l'API de stockage objet sélectionné (Amazon S3, Azure Blob, IBM Cloud Object Storage).

En outre, un groupe de courtiers en données a besoin d'une connexion Internet sortante sur le port 443 pour communiquer avec le service de copie et de synchronisation BlueXP et contacter quelques autres services et référentiels.

Pour en savoir plus, link:reference-networking.html["examiner les besoins en matière de mise en réseau"].



=== Puis-je utiliser un serveur proxy avec le courtier de données ?

Oui.

La copie et la synchronisation BlueXP prennent en charge les serveurs proxy avec ou sans authentification de base. Si vous spécifiez un serveur proxy lorsque vous déployez un courtier de données, tout le trafic HTTP et HTTPS du courtier de données est acheminé via le proxy. Notez que le trafic non HTTP tel que NFS ou SMB ne peut pas être routé via un serveur proxy.

La seule limitation du serveur proxy est liée au chiffrement des données à la volée avec une relation de synchronisation NFS ou Azure NetApp Files. Les données cryptées sont envoyées via HTTPS et ne sont pas routables via un serveur proxy.



== Synchronisation des données

Les questions suivantes concernent le fonctionnement de la synchronisation des données.



=== À quelle fréquence la synchronisation se produit-elle ?

Le planning par défaut est défini pour la synchronisation quotidienne. Après la synchronisation initiale, vous pouvez :

* Modifiez le programme de synchronisation en fonction du nombre de jours, d'heures ou de minutes souhaité
* Désactivez le programme de synchronisation
* Supprimer le programme de synchronisation (aucune donnée ne sera perdue ; seule la relation de synchronisation sera supprimée)




=== Quel est le programme de synchronisation minimal ?

Vous pouvez planifier une relation pour synchroniser les données aussi souvent que toutes les 1 minute.



=== Le groupe de courtier de données est-il réessaie-t-il lorsqu'un fichier ne se synchronise pas ? Ou est-ce que ce délai ?

Un groupe de courtiers de données n'expire pas lorsqu'un seul fichier ne parvient pas à être transféré. Le groupe de courtiers de données tente 3 fois de nouveau avant de sauter le fichier. La valeur de la nouvelle tentative est configurable dans les paramètres d'une relation de synchronisation.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["Découvrez comment modifier les paramètres d'une relation de synchronisation"].



=== Que se passe-t-il si j'ai un très grand jeu de données ?

Si un seul répertoire contient 600 000 fichiers ou plus,link:task-get-help.html["Contactez-nous"] afin que nous puissions vous aider à configurer le groupe de courtiers de données pour gérer la charge utile.  Nous devrons peut-être ajouter de la mémoire supplémentaire au groupe de courtiers de données.

Notez que le nombre total de fichiers dans le point de montage n'est pas limité. La mémoire supplémentaire est requise pour les grands répertoires contenant 600,000 fichiers ou plus, quel que soit leur niveau dans la hiérarchie (répertoire supérieur ou sous-répertoire).



== Sécurité

Les questions suivantes ont trait à la sécurité.



=== La copie et la synchronisation BlueXP sont-elles sécurisées ?

Oui. Toute la connectivité réseau du service de copie et de synchronisation BlueXP s'effectue à l'aide de https://aws.amazon.com/sqs/["Service SQS (simple Queue) d'Amazon"^].

Toutes les communications entre le groupe de courtier en données et Amazon S3, Azure Blob, Google Cloud Storage et IBM Cloud Object Storage sont effectuées via le protocole HTTPS.

Si vous utilisez la copie et la synchronisation BlueXP avec des systèmes sur site (source ou destination), nous vous recommandons plusieurs options de connectivité :

* Une connexion AWS Direct Connect, Azure ExpressRoute ou Google Cloud Interconnect, qui n'est pas routée par Internet (et ne peut communiquer qu'avec les réseaux cloud que vous spécifiez)
* Une connexion VPN entre votre passerelle sur site et vos réseaux cloud
* Pour un transfert de données plus sécurisé avec des compartiments S3, le stockage Azure Blob ou Google Cloud Storage, un terminal Amazon Private S3, des terminaux de service Azure Virtual Network ou Private Google Access peuvent être établis.


L'une de ces méthodes établit une connexion sécurisée entre vos serveurs NAS sur site et un groupe de courtiers de données de copie et de synchronisation BlueXP.



=== Les données sont-elles chiffrées par la copie et la synchronisation BlueXP ?

* La copie et la synchronisation BlueXP prennent en charge le chiffrement des données à la volée entre les serveurs NFS source et cible. link:task-nfs-encryption.html["En savoir plus >>"].
* Pour les PME, la copie et la synchronisation BlueXP prennent en charge les données SMB 3.0 et 3.11 que vous avez chiffrées côté serveur. La copie et la synchronisation BlueXP copie les données chiffrées de la source vers la cible où les données restent chiffrées.
+
La copie et la synchronisation BlueXP ne peuvent pas chiffrer les données SMB eux-mêmes.

* Lorsqu'un compartiment Amazon S3 est la cible d'une relation synchrone, vous pouvez choisir d'activer le chiffrement des données à l'aide du chiffrement AWS KMS ou AES-256.
* Lorsqu'un compartiment Google Storage est la cible dans une relation de synchronisation, vous pouvez choisir d'utiliser la clé de chiffrement par défaut gérée par Google ou votre propre clé KMS.




== Autorisations

Les questions suivantes concernent les autorisations de données.



=== Les autorisations de données SMB sont-elles synchronisées vers l'emplacement cible ?

Vous pouvez configurer la copie et la synchronisation BlueXP pour préserver les listes de contrôle d'accès (ACL) entre un partage SMB source et un partage SMB cible, et d'un partage SMB source vers le stockage objet (à l'exception de ONTAP S3).


NOTE: La copie et la synchronisation BlueXP ne prennent pas en charge la copie de listes de contrôle d'accès depuis le stockage objet vers les partages SMB.

link:task-copying-acls.html["Découvrez comment copier des listes de contrôle d'accès entre partages SMB"].



=== Les autorisations de données NFS sont-elles synchronisées vers l'emplacement cible ?

La copie et la synchronisation BlueXP copie automatiquement les autorisations NFS entre les serveurs NFS de la manière suivante :

* NFS version 3 : la copie et la synchronisation BlueXP copie les autorisations et le propriétaire du groupe d'utilisateurs.
* NFS version 4 : copie et synchronisation BlueXP copie les listes de contrôle d'accès.




== Métadonnées de stockage objet



=== Quels types de relations de synchronisation préservent les métadonnées du stockage objet ?

La copie et la synchronisation BlueXP copie les métadonnées de stockage objet de la source vers la cible pour les types de relations de synchronisation suivants :

* Amazon S3 -> Amazon S3 ^1^
* Amazon S3 -> StorageGRID
* StorageGRID -> Amazon S3
* StorageGRID -> StorageGRID
* StorageGRID -> Google Cloud Storage
* Google Cloud Storage -> StorageGRID ^1^
* Google Cloud Storage -> stockage objet cloud IBM ^1^
* Google Cloud Storage -> Amazon S3 ^1^
* Amazon S3 -> Google Cloud Storage
* IBM Cloud Object Storage -> Google Cloud Storage
* StorageGRID -> stockage objet cloud IBM
* IBM Cloud Object Storage -> StorageGRID
* IBM Cloud Object Storage -> stockage objet cloud IBM


^1^ pour ces relations de synchronisation, vous devez le faire link:task-creating-relationships.html["Activez le paramètre Copier pour les objets lorsque vous créez la relation de synchronisation"].



=== Quels types de métadonnées sont répliquées lors des synchronisations et où NFS ou SMB sont la source ?

Les métadonnées telles que l'ID utilisateur, l'heure de modification, le temps d'accès et le GID sont répliquées par défaut. Les utilisateurs peuvent choisir de répliquer une liste de contrôle d'accès à partir de CIFS en la marquant comme requis lors de la création d'une relation de synchronisation.



== Performance

Les questions suivantes concernent les performances de la copie et de la synchronisation BlueXP.



=== Que représente l'indicateur de progression d'une relation de synchronisation ?

La relation de synchronisation indique le débit de la carte réseau du groupe de courtiers de données. Si vous accélérez les performances de synchronisation en utilisant plusieurs courtiers de données, le débit est la somme de tout le trafic. Ce débit est actualisé toutes les 20 secondes.



=== J'ai des problèmes de performances. Pouvons-nous limiter le nombre de transferts simultanés ?

Si vous avez des fichiers très volumineux (plusieurs Tbs chacun), le processus de transfert peut prendre beaucoup de temps et les performances peuvent être affectées.

Limiter le nombre de transferts simultanés peut être utile. link:task-get-help.html["Contactez-nous pour obtenir de l'aide"] .



=== Pourquoi les performances avec Azure NetApp Files sont-elles faibles ?

Lorsque vous synchronisez les données depuis ou vers Azure NetApp Files, vous risquez de subir des défaillances et des problèmes de performances si le niveau de service des disques est Standard.

Définissez le niveau de service sur Premium ou Ultra pour améliorer les performances de synchronisation.

https://docs.microsoft.com/en-us/azure/azure-netapp-files/azure-netapp-files-service-levels#throughput-limits["En savoir plus sur le débit et les niveaux de service de Azure NetApp Files"^].



=== Combien de courtiers de données sont requis dans un groupe ?

Lorsque vous créez une nouvelle relation, vous commencez par un courtier de données unique dans un groupe (sauf si vous avez sélectionné un courtier de données existant appartenant à une relation de synchronisation accélérée). Dans de nombreux cas, un seul courtier de données peut répondre aux exigences de performance d'une relation de synchronisation. Si ce n'est pas le cas, vous pouvez accélérer la synchronisation en ajoutant des courtiers de données supplémentaires au groupe. Mais vous devez d'abord vérifier d'autres facteurs qui peuvent avoir un impact sur les performances de synchronisation.

Plusieurs facteurs peuvent avoir un impact sur les performances de transfert de données. Les performances globales de la synchronisation peuvent être affectées en raison de la bande passante du réseau, de la latence et de la topologie du réseau, ainsi que des spécifications des VM du courtier de données et des performances du système de stockage. Par exemple, un seul courtier de données d'un groupe peut atteindre 100 Mo/s, tandis que le débit du disque sur la cible ne peut autoriser que 64 Mo/s. Par conséquent, le groupe de courtiers de données essaie toujours de copier les données, mais la cible ne peut pas répondre aux performances du groupe de courtiers de données.

Assurez-vous donc de vérifier les performances de votre réseau et le débit du disque sur la cible.

Vous pouvez alors envisager d'accélérer la synchronisation en ajoutant un courtier de données supplémentaire à un groupe pour partager la charge de cette relation. link:task-managing-relationships.html#accelerate-sync-performance["Découvrez comment accélérer les performances de synchronisation"].



== Suppression de choses

Les questions suivantes concernent la suppression des relations de synchronisation et des données des sources et des cibles.



=== Que se passe-t-il si je supprime ma relation de copie et de synchronisation BlueXP ?

La suppression d'une relation arrête toutes les synchronisations de données futures et met fin au paiement. Toutes les données synchronisées sur la cible restent en l'état.



=== Que se passe-t-il si je supprime quelque chose de mon serveur source ? Est-il également supprimé de la cible ?

Par défaut, si vous disposez d'une relation de synchronisation active, l'élément supprimé sur le serveur source n'est pas supprimé de la cible lors de la prochaine synchronisation. Toutefois, il existe une option dans les paramètres de synchronisation pour chaque relation. Vous pouvez définir que la copie et la synchronisation BlueXP suppriment les fichiers à l'emplacement cible s'ils ont été supprimés de la source.

link:task-managing-relationships.html#change-the-settings-for-a-sync-relationship["Découvrez comment modifier les paramètres d'une relation de synchronisation"].



=== Que se passe-t-il si je supprime quelque chose de ma cible ? Est-il supprimé de ma source ?

Si un élément est supprimé de la cible, il ne sera pas supprimé de la source. La relation est unidirectionnelle, de la source à la cible. Lors du cycle de synchronisation suivant, la copie et la synchronisation BlueXP compare la source et la cible, identifie l'élément manquant, et la copie et la synchronisation BlueXP les copient de la source vers la cible.



== Dépannage

https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Cloud_Sync/Cloud_Sync_FAQ:_Support_and_Troubleshooting["Base de connaissances NetApp : FAQ sur la copie et la synchronisation BlueXP : support et résolution de problèmes"^]



== Data broker plongez en profondeur

La question suivante concerne le courtier de données.



=== Pouvez-vous expliquer l'architecture du data broker ?

Bien sûr. Voici les points les plus importants :

* Le courtier de données est une application node.js exécutée sur un hôte Linux.
* La copie et la synchronisation BlueXP déploient le courtier en données comme suit :
+
** AWS : à partir d'un modèle AWS CloudFormation
** Azure : d'Azure Resource Manager
** Google : à partir de Google Cloud Deployment Manager
** Si vous utilisez votre propre hôte Linux, vous devez installer manuellement le logiciel


* Le logiciel Data Broker se met automatiquement à niveau vers la dernière version.
* Le data broker utilise AWS SQS comme canal de communication fiable et sécurisé et pour le contrôle et la surveillance. Les LP fournissent également une couche de persistance.
* Vous pouvez ajouter des courtiers de données supplémentaires à un groupe pour augmenter la vitesse de transfert et ajouter une haute disponibilité. La résilience des services est assurée en cas de défaillance d'un courtier de données.

