---
sidebar: sidebar 
permalink: task-licensing.html 
keywords: license, subscription, registering, subscribing, subscribing in aws, subscribing in azure, subscribing to aws, subscribing to azure, aws marketplace, azure marketplace, netapp license, byol license, purchase a license, license settings, pay for relationships, paygo, annual, pay-as-you-go 
summary: 'Il existe deux façons de payer les relations de synchronisation après la fin de votre essai gratuit de 14 jours. La première option consiste à payer en fonction de l"utilisation. La deuxième option consiste à acheter des licences directement auprès de NetApp.' 
---
= Payez les relations synchronisées une fois votre essai gratuit terminé
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Il existe deux façons de payer les relations de synchronisation après la fin de votre essai gratuit de 14 jours. La première option consiste à vous abonner à AWS ou Azure pour payer à votre gré ou à payer annuellement. La deuxième option consiste à acheter des licences directement auprès de NetApp.

Vous pouvez vous abonner à AWS Marketplace ou à Azure Marketplace. Vous ne pouvez pas vous abonner des deux.

Vous avez la possibilité d'utiliser les licences de NetApp avec un abonnement Marketplace. Par exemple, si vous disposez de 25 relations de synchronisation, vous pouvez payer les 20 premières relations de synchronisation à l'aide d'une licence, puis effectuer des opérations de paiement à la demande à partir d'AWS ou d'Azure avec les 5 autres relations de synchronisation.

link:concept-licensing.html["En savoir plus sur le fonctionnement des licences"].

Si vous ne payez pas immédiatement après la fin de votre essai gratuit, vous ne pourrez pas créer de relations supplémentaires. Les relations existantes ne sont pas supprimées, mais vous ne pouvez pas y apporter de modifications tant que vous n'êtes pas abonné ou que vous n'avez pas saisi de licence.

Les licences doivent être gérées par le biais de la copie et de la synchronisation BlueXP ou du site web concerné et *non* par le biais d'un portefeuille digital.



== [[aws]]Abonnez-vous à AWS

AWS vous permet de payer à votre gré ou de payer chaque année.

.Les étapes à payer en tant que vous-même
. Dans le menu de navigation BlueXP , sélectionnez *mobilité > Copier et synchroniser*.
. Sélectionnez *Licence*.
. Sélectionnez *AWS*.
. Sélectionnez *s'abonner*, puis *Continuer*.
. Abonnez-vous à AWS Marketplace, puis reconnectez-vous au service de copie et de synchronisation BlueXP pour terminer l'enregistrement.
+
La vidéo suivante montre le processus :

+
.Abonnez-vous à la copie et à la synchronisation BlueXP  depuis AWS Marketplace
video::796ffd6d-cade-4750-8504-b24c010b225d[panopto]


.Étapes à payer annuellement
. https://aws.amazon.com/marketplace/pp/B06XX5V3M2["Accédez à la page AWS Marketplace"^].
. Sélectionnez *Continuer pour s'inscrire*.
. Sélectionnez vos options de contrat, puis sélectionnez *Créer un contrat*.




== [[Azure]]Abonnez-vous à Azure

Azure vous permet de payer à votre gré ou de payer chaque année.

.Ce dont vous avez besoin
Un compte utilisateur Azure disposant des autorisations Contributeur ou Propriétaire dans l'abonnement correspondant.

.Étapes
. Dans le menu de navigation BlueXP , sélectionnez *mobilité > Copier et synchroniser*.
. Sélectionnez *Licence*.
. Sélectionnez *Azure*.
. Sélectionnez *s'abonner*, puis *Continuer*.
. Dans le portail Azure, sélectionnez *Créer*, sélectionnez vos options, puis *s'abonner*.
+
Sélectionnez *mensuel* pour payer par heure, ou *annuel* pour payer une année avant.

. Une fois le déploiement terminé, sélectionnez le nom de la ressource SaaS dans la fenêtre contextuelle de notification.
. Sélectionnez *configurer le compte* pour revenir à la copie et à la synchronisation BlueXP.
+
La vidéo suivante montre le processus :

+
.Abonnez-vous à la copie et à la synchronisation BlueXP  depuis Azure Marketplace
video::a6a39447-b7b1-42f6-9c89-b24c010b21b9[panopto]




== [[licenses]]Achetez des licences auprès de NetApp et ajoutez-les à la copie et à la synchronisation BlueXP 

Pour payer vos relations de synchronisation au préalable, vous devez acheter une ou plusieurs licences et les ajouter au service de copie et de synchronisation BlueXP.

.Ce dont vous avez besoin
Vous devez disposer du numéro de série correspondant à votre licence, ainsi que du nom d'utilisateur et du mot de passe du compte sur le site de support NetApp auquel la licence est associée.

.Étapes
. Achetez une licence par mailto:ng-cloudsync-contact@netapp.com?subject=Cloud%20Sync%20Service%20-%20BYOL%20License%20Purchase%20Request[contacter NetApp].
. Dans le menu de navigation BlueXP , sélectionnez *mobilité > Copier et synchroniser*.
. Sélectionnez *Licence*.
. Sélectionnez *Ajouter une licence* et ajoutez les informations requises :
+
.. Saisissez le numéro de série.
.. Sélectionnez le compte sur le site de support NetApp associé à la licence que vous ajoutez :
+
*** Si votre compte a déjà été ajouté à BlueXP, sélectionnez-le dans la liste déroulante.
*** Si votre compte n'a pas encore été ajouté, sélectionnez *Ajouter les informations d'identification NSS*, entrez le nom d'utilisateur et le mot de passe, sélectionnez *s'inscrire*, puis sélectionnez-le dans la liste déroulante.


.. Sélectionnez *Ajouter*.






== Mettre à jour une licence

Si vous avez étendu une licence de copie et de synchronisation BlueXP que vous avez achetée auprès de NetApp, la nouvelle date d'expiration ne se mettra pas à jour automatiquement dans la copie et la synchronisation BlueXP. Vous devez ajouter de nouveau la licence pour actualiser la date d'expiration. Les licences doivent être gérées par le biais de la copie et de la synchronisation BlueXP ou du site web concerné et *non* par le biais d'un portefeuille digital.

.Étapes
. Dans le menu de navigation BlueXP , sélectionnez *mobilité > Copier et synchroniser*.
. Sélectionnez *Licence*.
. Sélectionnez *Ajouter une licence* et ajoutez les informations requises :
+
.. Saisissez le numéro de série.
.. Sélectionnez le compte du site de support NetApp associé à la licence que vous ajoutez.
.. Sélectionnez *Ajouter*.




.Résultat
La copie et la synchronisation BlueXP mettent à jour la licence existante avec la nouvelle date d'expiration.
